# Generated by Django 6.0.5 on 2026-05-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('origine', models.CharField(max_length=100)),
                ('est_dangereux', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaux.espece')),
            ],
        ),
    ]
